import * as SQLite from "expo-sqlite";

export type CardRow = {
  id: number;
  name: string;
  credit_limit: number;
  current_balance: number;
  apr: number;
  min_payment: number;
  due_date: string;
  opening_date: string;
};

export type PaymentRow = {
  id: number;
  card_id: number;
  amount: number;
  paid_at: string;
  balance_after: number;
};

export type LoanPromotionRow = {
  id: number;
  name: string;
  amount_borrowed: number;
  current_balance: number;
  start_date: string;
  end_date: string;
  monthly_payment_target: number;
  purchases_this_month: number;
  purchases_month: string;
  interest_free_expiration: string;
  notes: string;
};

export type LoanPaymentRow = {
  id: number;
  loan_id: number;
  amount: number;
  paid_at: string;
  balance_after: number;
};

export type ReminderSourceType = "manual" | "card" | "loan" | "promotion";

export type ReminderRow = {
  id: number;
  title: string;
  amount_due: number;
  due_date: string;
  notes: string;
  repeat_monthly: number;
  is_paid: number;
  paid_at: string | null;
  payment_source: string;
  source_type: ReminderSourceType;
  source_id: number | null;
  created_at: string;
  updated_at: string;
};

export type ReminderPaymentHistoryRow = {
  id: number;
  reminder_id: number;
  paid_at: string;
  amount: number;
  payment_source: string;
};

const db = SQLite.openDatabaseSync("finpilot_mobile.db");
let initialized = false;

const USER_BASE_CREDIT_SCORE_KEY = "user_base_credit_score";

export function initDb() {
  if (initialized) return;
  db.execSync(`
    PRAGMA journal_mode = WAL;
    CREATE TABLE IF NOT EXISTS cards (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      credit_limit REAL NOT NULL,
      current_balance REAL NOT NULL,
      apr REAL NOT NULL,
      min_payment REAL NOT NULL,
      due_date TEXT NOT NULL,
      opening_date TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      card_id INTEGER NOT NULL,
      amount REAL NOT NULL,
      paid_at TEXT NOT NULL,
      balance_after REAL NOT NULL,
      FOREIGN KEY(card_id) REFERENCES cards(id) ON DELETE CASCADE
    );
    CREATE TABLE IF NOT EXISTS score_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      estimated_score INTEGER NOT NULL,
      utilization REAL NOT NULL,
      created_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS loan_promotions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      amount_borrowed REAL NOT NULL,
      current_balance REAL NOT NULL,
      start_date TEXT NOT NULL,
      end_date TEXT NOT NULL,
      monthly_payment_target REAL NOT NULL,
      purchases_this_month REAL NOT NULL DEFAULT 0,
      purchases_month TEXT NOT NULL DEFAULT '',
      interest_free_expiration TEXT NOT NULL,
      notes TEXT NOT NULL DEFAULT ''
    );
    CREATE TABLE IF NOT EXISTS loan_payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      loan_id INTEGER NOT NULL,
      amount REAL NOT NULL,
      paid_at TEXT NOT NULL,
      balance_after REAL NOT NULL,
      FOREIGN KEY(loan_id) REFERENCES loan_promotions(id) ON DELETE CASCADE
    );
    CREATE TABLE IF NOT EXISTS app_settings (
      key TEXT PRIMARY KEY NOT NULL,
      value TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS payment_reminders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      amount_due REAL NOT NULL,
      due_date TEXT NOT NULL,
      notes TEXT NOT NULL DEFAULT '',
      repeat_monthly INTEGER NOT NULL DEFAULT 0,
      is_paid INTEGER NOT NULL DEFAULT 0,
      paid_at TEXT,
      payment_source TEXT NOT NULL DEFAULT '',
      source_type TEXT NOT NULL DEFAULT 'manual',
      source_id INTEGER,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(source_type, source_id)
    );
    CREATE TABLE IF NOT EXISTS reminder_payment_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      reminder_id INTEGER NOT NULL,
      paid_at TEXT NOT NULL,
      amount REAL NOT NULL,
      payment_source TEXT NOT NULL DEFAULT '',
      FOREIGN KEY(reminder_id) REFERENCES payment_reminders(id) ON DELETE CASCADE
    );
  `);
  ensureLoanPurchasesColumn();
  ensureLoanPurchasesMonthColumn();
  ensureReminderSchema();

  const count = db.getFirstSync<{ count: number }>("SELECT COUNT(*) as count FROM cards");
  // Keep "Sam Faz" for branding only (icon/splash), not as a seeded card record.
  db.runSync(`UPDATE cards SET name = 'Amex Platinum' WHERE name = 'Amex Sam Faz'`);
  if ((count?.count ?? 0) === 0) seedDemoData();
  syncAutoGeneratedRemindersForAll();
  initialized = true;
}

function seedDemoData() {
  const now = new Date();
  db.runSync(
    `INSERT INTO cards (name, credit_limit, current_balance, apr, min_payment, due_date, opening_date)
     VALUES (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?)`,
    "Amex Platinum",
    8200,
    2150,
    21.99,
    75,
    new Date(now.getTime() + 7 * 86400000).toISOString(),
    new Date(now.getFullYear() - 4, 2, 10).toISOString(),
    "Blue Orbit",
    4200,
    980,
    27.99,
    45,
    new Date(now.getTime() + 12 * 86400000).toISOString(),
    new Date(now.getFullYear() - 2, 8, 4).toISOString(),
    "Nova Flex",
    2600,
    430,
    19.99,
    30,
    new Date(now.getTime() + 16 * 86400000).toISOString(),
    new Date(now.getFullYear() - 1, 5, 22).toISOString()
  );

  const cards = getCards();
  cards.forEach((card, index) => {
    const paid = 120 + index * 35;
    const balanceAfter = Math.max(0, card.current_balance - paid);
    db.runSync(
      "INSERT INTO payments (card_id, amount, paid_at, balance_after) VALUES (?, ?, ?, ?)",
      card.id,
      paid,
      new Date(now.getTime() - (index + 2) * 86400000 * 12).toISOString(),
      balanceAfter
    );
  });

  db.runSync(
    `INSERT INTO loan_promotions
     (name, amount_borrowed, current_balance, start_date, end_date, monthly_payment_target, purchases_this_month, purchases_month, interest_free_expiration, notes)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    "0% APR Balance Transfer",
    4000,
    3200,
    new Date(now.getFullYear() - 1, 4, 12).toISOString(),
    new Date(now.getFullYear(), 4, 12).toISOString(),
    320,
    0,
    getCurrentMonthKey(),
    new Date(now.getFullYear(), 4, 12).toISOString(),
    "Transfer promo to avoid high APR"
  );
}

function ensureLoanPurchasesColumn() {
  const columns = db.getAllSync<{ name: string }>("PRAGMA table_info(loan_promotions)");
  const hasPurchasesColumn = columns.some((col) => col.name === "purchases_this_month");
  if (!hasPurchasesColumn) {
    db.runSync("ALTER TABLE loan_promotions ADD COLUMN purchases_this_month REAL NOT NULL DEFAULT 0");
  }
}

function ensureLoanPurchasesMonthColumn() {
  const columns = db.getAllSync<{ name: string }>("PRAGMA table_info(loan_promotions)");
  const hasPurchasesMonthColumn = columns.some((col) => col.name === "purchases_month");
  if (!hasPurchasesMonthColumn) {
    db.runSync("ALTER TABLE loan_promotions ADD COLUMN purchases_month TEXT NOT NULL DEFAULT ''");
  }
}

function getCurrentMonthKey() {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  return `${now.getFullYear()}-${month}`;
}

function ensureReminderSchema() {
  const reminderColumns = db.getAllSync<{ name: string }>("PRAGMA table_info(payment_reminders)");
  const neededColumns: Array<{ name: string; sql: string }> = [
    { name: "payment_source", sql: "ALTER TABLE payment_reminders ADD COLUMN payment_source TEXT NOT NULL DEFAULT ''" },
    { name: "source_type", sql: "ALTER TABLE payment_reminders ADD COLUMN source_type TEXT NOT NULL DEFAULT 'manual'" },
    { name: "source_id", sql: "ALTER TABLE payment_reminders ADD COLUMN source_id INTEGER" },
    { name: "created_at", sql: "ALTER TABLE payment_reminders ADD COLUMN created_at TEXT NOT NULL DEFAULT ''" },
    { name: "updated_at", sql: "ALTER TABLE payment_reminders ADD COLUMN updated_at TEXT NOT NULL DEFAULT ''" },
  ];
  neededColumns.forEach((column) => {
    if (!reminderColumns.some((c) => c.name === column.name)) {
      db.runSync(column.sql);
    }
  });
  const nowIso = new Date().toISOString();
  db.runSync("UPDATE payment_reminders SET created_at = COALESCE(NULLIF(created_at, ''), ?) WHERE created_at IS NULL OR created_at = ''", nowIso);
  db.runSync("UPDATE payment_reminders SET updated_at = COALESCE(NULLIF(updated_at, ''), ?) WHERE updated_at IS NULL OR updated_at = ''", nowIso);
}

function getNextMonthlyDueDate(baseIsoDate: string) {
  const now = new Date();
  const base = new Date(baseIsoDate);
  const day = Number.isFinite(base.getDate()) ? base.getDate() : now.getDate();
  let year = now.getFullYear();
  let month = now.getMonth();
  let candidate = new Date(year, month, day, 9, 0, 0, 0);
  if (candidate.getTime() < now.getTime()) {
    month += 1;
    if (month > 11) {
      month = 0;
      year += 1;
    }
    candidate = new Date(year, month, day, 9, 0, 0, 0);
  }
  return candidate.toISOString();
}

function upsertAutoReminder(input: {
  sourceType: ReminderSourceType;
  sourceId: number;
  title: string;
  amountDue: number;
  dueDate: string;
  notes: string;
  repeatMonthly: number;
}) {
  const nowIso = new Date().toISOString();
  const existing = db.getFirstSync<ReminderRow>(
    "SELECT * FROM payment_reminders WHERE source_type = ? AND source_id = ?",
    input.sourceType,
    input.sourceId
  );
  if (existing) {
    const shouldKeepPaid = existing.is_paid === 1 && new Date(existing.due_date).getTime() >= new Date(input.dueDate).getTime();
    db.runSync(
      `UPDATE payment_reminders
       SET title = ?, amount_due = ?, due_date = ?, notes = ?, repeat_monthly = ?, is_paid = ?, paid_at = ?, updated_at = ?
       WHERE id = ?`,
      input.title,
      input.amountDue,
      input.dueDate,
      input.notes,
      input.repeatMonthly,
      shouldKeepPaid ? existing.is_paid : 0,
      shouldKeepPaid ? existing.paid_at : null,
      nowIso,
      existing.id
    );
    return;
  }
  db.runSync(
    `INSERT INTO payment_reminders
      (title, amount_due, due_date, notes, repeat_monthly, is_paid, paid_at, payment_source, source_type, source_id, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, 0, NULL, '', ?, ?, ?, ?)`,
    input.title,
    input.amountDue,
    input.dueDate,
    input.notes,
    input.repeatMonthly,
    input.sourceType,
    input.sourceId,
    nowIso,
    nowIso
  );
}

function syncCardReminder(card: CardRow) {
  const amountDue = Math.max(0, Number(card.min_payment) || 0);
  upsertAutoReminder({
    sourceType: "card",
    sourceId: card.id,
    title: `${card.name} Payment`,
    amountDue,
    dueDate: card.due_date,
    notes: "Auto reminder from credit card",
    repeatMonthly: 1,
  });
}

function syncLoanReminder(loan: LoanPromotionRow) {
  const amountDue = Math.max(0, Number(loan.monthly_payment_target) || 0);
  upsertAutoReminder({
    sourceType: "loan",
    sourceId: loan.id,
    title: `${loan.name} Promotion Payment`,
    amountDue,
    dueDate: getNextMonthlyDueDate(loan.end_date || loan.interest_free_expiration),
    notes: "Auto reminder from loan or promotion",
    repeatMonthly: 1,
  });
}

function syncAutoGeneratedRemindersForAll() {
  const cards = db.getAllSync<CardRow>("SELECT * FROM cards");
  cards.forEach(syncCardReminder);
  const loans = db.getAllSync<LoanPromotionRow>("SELECT * FROM loan_promotions");
  loans.forEach(syncLoanReminder);
}

export function getCards(): CardRow[] {
  initDb();
  return db.getAllSync<CardRow>("SELECT * FROM cards ORDER BY id DESC");
}

export function addCard(input: Omit<CardRow, "id">) {
  initDb();
  const result = db.runSync(
    `INSERT INTO cards (name, credit_limit, current_balance, apr, min_payment, due_date, opening_date)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    input.name,
    input.credit_limit,
    input.current_balance,
    input.apr,
    input.min_payment,
    input.due_date,
    input.opening_date
  );
  const inserted = db.getFirstSync<CardRow>("SELECT * FROM cards WHERE id = ?", result.lastInsertRowId);
  if (inserted) syncCardReminder(inserted);
}

export function updateCard(id: number, patch: Partial<Omit<CardRow, "id">>) {
  initDb();
  const current = db.getFirstSync<CardRow>("SELECT * FROM cards WHERE id = ?", id);
  if (!current) return;
  const next = {
    ...current,
    ...patch,
  };
  db.runSync(
    `UPDATE cards
     SET name = ?, credit_limit = ?, current_balance = ?, apr = ?, min_payment = ?, due_date = ?, opening_date = ?
     WHERE id = ?`,
    next.name,
    next.credit_limit,
    next.current_balance,
    next.apr,
    next.min_payment,
    next.due_date,
    next.opening_date,
    id
  );
  const updated = db.getFirstSync<CardRow>("SELECT * FROM cards WHERE id = ?", id);
  if (updated) syncCardReminder(updated);
}

export function deleteCard(id: number) {
  initDb();
  db.runSync("DELETE FROM payments WHERE card_id = ?", id);
  db.runSync("DELETE FROM payment_reminders WHERE source_type = 'card' AND source_id = ?", id);
  db.runSync("DELETE FROM cards WHERE id = ?", id);
}

export function addPayment(cardId: number, amount: number, paidAt: string) {
  initDb();
  const card = db.getFirstSync<CardRow>("SELECT * FROM cards WHERE id = ?", cardId);
  if (!card) return;
  const balanceAfter = Math.max(0, card.current_balance - amount);
  db.runSync("UPDATE cards SET current_balance = ? WHERE id = ?", balanceAfter, cardId);
  db.runSync(
    `INSERT INTO payments (card_id, amount, paid_at, balance_after) VALUES (?, ?, ?, ?)`,
    cardId,
    amount,
    paidAt,
    balanceAfter
  );
}

export function getPayments(): (PaymentRow & { card_name: string })[] {
  initDb();
  return db.getAllSync<PaymentRow & { card_name: string }>(
    `SELECT p.*, c.name as card_name
     FROM payments p
     JOIN cards c ON c.id = p.card_id
     ORDER BY p.paid_at DESC`
  );
}

export function dashboardSummary() {
  initDb();
  const cards = getCards();
  const loans = getLoans();
  const totalDebt = cards.reduce((s, c) => s + c.current_balance, 0);
  const loanDebt = loans.reduce((s, l) => s + l.current_balance, 0);
  const totalCredit = cards.reduce((s, c) => s + c.credit_limit, 0);
  const utilization = totalCredit > 0 ? totalDebt / totalCredit : 0;
  const endingSoonCount = loans.filter((l) => {
    const months = getRemainingMonths(l.interest_free_expiration);
    return months >= 0 && months <= 2;
  }).length;
  const endingSoonLoans = loans
    .filter((l) => {
      const months = getRemainingMonths(l.interest_free_expiration);
      return months >= 0 && months <= 2;
    })
    .map((l) => ({ id: l.id, name: l.name, monthsLeft: getRemainingMonths(l.interest_free_expiration), balance: l.current_balance }))
    .slice(0, 3);
  return {
    cards,
    loans,
    totalDebt: totalDebt + loanDebt,
    cardDebt: totalDebt,
    loanDebt,
    totalCredit,
    utilization,
    endingSoonCount,
    endingSoonLoans,
  };
}

export function getLoans(): LoanPromotionRow[] {
  initDb();
  const monthKey = getCurrentMonthKey();
  db.runSync(
    `UPDATE loan_promotions
     SET purchases_this_month = 0, purchases_month = ?
     WHERE purchases_month != ?`,
    monthKey,
    monthKey
  );
  return db.getAllSync<LoanPromotionRow>("SELECT * FROM loan_promotions ORDER BY interest_free_expiration ASC");
}

export function addLoan(
  input: Omit<LoanPromotionRow, "id" | "current_balance" | "monthly_payment_target" | "purchases_this_month" | "purchases_month"> & {
    current_balance?: number;
    monthly_payment_target?: number;
    purchases_this_month?: number;
  }
) {
  initDb();
  const balance = Number.isFinite(input.current_balance) ? Number(input.current_balance) : input.amount_borrowed;
  const months = Math.max(1, getRemainingMonths(input.interest_free_expiration));
  const monthly = Number.isFinite(input.monthly_payment_target) && (input.monthly_payment_target ?? 0) > 0
    ? Number(input.monthly_payment_target)
    : balance / months;
  const result = db.runSync(
    `INSERT INTO loan_promotions
      (name, amount_borrowed, current_balance, start_date, end_date, monthly_payment_target, purchases_this_month, purchases_month, interest_free_expiration, notes)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    input.name,
    input.amount_borrowed,
    balance,
    input.start_date,
    input.end_date,
    monthly,
    input.purchases_this_month ?? 0,
    getCurrentMonthKey(),
    input.interest_free_expiration,
    input.notes ?? ""
  );
  const inserted = db.getFirstSync<LoanPromotionRow>("SELECT * FROM loan_promotions WHERE id = ?", result.lastInsertRowId);
  if (inserted) syncLoanReminder(inserted);
}

export function updateLoan(id: number, patch: Partial<Omit<LoanPromotionRow, "id">>) {
  initDb();
  const current = db.getFirstSync<LoanPromotionRow>("SELECT * FROM loan_promotions WHERE id = ?", id);
  if (!current) return;
  const next = { ...current, ...patch };
  db.runSync(
    `UPDATE loan_promotions
     SET name = ?, amount_borrowed = ?, current_balance = ?, start_date = ?, end_date = ?, monthly_payment_target = ?, purchases_this_month = ?, purchases_month = ?, interest_free_expiration = ?, notes = ?
     WHERE id = ?`,
    next.name,
    next.amount_borrowed,
    next.current_balance,
    next.start_date,
    next.end_date,
    next.monthly_payment_target,
    next.purchases_this_month,
    next.purchases_month,
    next.interest_free_expiration,
    next.notes,
    id
  );
  const updated = db.getFirstSync<LoanPromotionRow>("SELECT * FROM loan_promotions WHERE id = ?", id);
  if (updated) syncLoanReminder(updated);
}

export function setLoanPurchasesThisMonth(id: number, purchasesThisMonth: number) {
  initDb();
  db.runSync(
    "UPDATE loan_promotions SET purchases_this_month = ?, purchases_month = ? WHERE id = ?",
    Math.max(0, purchasesThisMonth),
    getCurrentMonthKey(),
    id
  );
}

export function deleteLoan(id: number) {
  initDb();
  db.runSync("DELETE FROM loan_payments WHERE loan_id = ?", id);
  db.runSync("DELETE FROM payment_reminders WHERE source_type = 'loan' AND source_id = ?", id);
  db.runSync("DELETE FROM loan_promotions WHERE id = ?", id);
}

export function addLoanPayment(loanId: number, amount: number, paidAt: string) {
  initDb();
  const loan = db.getFirstSync<LoanPromotionRow>("SELECT * FROM loan_promotions WHERE id = ?", loanId);
  if (!loan) return;
  const balanceAfter = Math.max(0, loan.current_balance - amount);
  const months = Math.max(1, getRemainingMonths(loan.interest_free_expiration));
  const monthly = balanceAfter > 0 ? balanceAfter / months : 0;
  db.runSync(
    "UPDATE loan_promotions SET current_balance = ?, monthly_payment_target = ? WHERE id = ?",
    balanceAfter,
    monthly,
    loanId
  );
  db.runSync(
    `INSERT INTO loan_payments (loan_id, amount, paid_at, balance_after) VALUES (?, ?, ?, ?)`,
    loanId,
    amount,
    paidAt,
    balanceAfter
  );
}

export function getLoanPayments(): (LoanPaymentRow & { loan_name: string })[] {
  initDb();
  return db.getAllSync<LoanPaymentRow & { loan_name: string }>(
    `SELECT p.*, l.name as loan_name
     FROM loan_payments p
     JOIN loan_promotions l ON l.id = p.loan_id
     ORDER BY p.paid_at DESC`
  );
}

export function getRemainingMonths(isoDate: string) {
  const now = new Date();
  const end = new Date(isoDate);
  const diffMs = end.getTime() - now.getTime();
  if (!Number.isFinite(diffMs)) return 0;
  return Math.max(0, Math.ceil(diffMs / (1000 * 60 * 60 * 24 * 30)));
}

/** User-entered real credit score (300–850), persisted locally. */
export function getUserBaseScore(): number | null {
  initDb();
  const row = db.getFirstSync<{ value: string }>(
    "SELECT value FROM app_settings WHERE key = ?",
    USER_BASE_CREDIT_SCORE_KEY
  );
  if (!row?.value) return null;
  const n = Number.parseInt(row.value, 10);
  if (!Number.isFinite(n) || n < 300 || n > 850) return null;
  return n;
}

export function setUserBaseScore(score: number) {
  initDb();
  const clamped = Math.max(300, Math.min(850, Math.round(score)));
  db.runSync(
    `INSERT INTO app_settings (key, value) VALUES (?, ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
    USER_BASE_CREDIT_SCORE_KEY,
    String(clamped)
  );
}

export function getReminders() {
  initDb();
  return db.getAllSync<ReminderRow>(
    `SELECT * FROM payment_reminders
     ORDER BY is_paid ASC, datetime(due_date) ASC, id DESC`
  );
}

export function addReminder(input: {
  title: string;
  amount_due: number;
  due_date: string;
  notes?: string;
  repeat_monthly?: boolean;
}) {
  initDb();
  const nowIso = new Date().toISOString();
  db.runSync(
    `INSERT INTO payment_reminders
      (title, amount_due, due_date, notes, repeat_monthly, is_paid, paid_at, payment_source, source_type, source_id, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, 0, NULL, '', 'manual', NULL, ?, ?)`,
    input.title.trim(),
    Math.max(0, input.amount_due),
    input.due_date,
    input.notes?.trim() ?? "",
    input.repeat_monthly ? 1 : 0,
    nowIso,
    nowIso
  );
}

export function updateReminder(
  id: number,
  patch: Partial<Pick<ReminderRow, "title" | "amount_due" | "due_date" | "notes" | "repeat_monthly" | "is_paid" | "paid_at" | "payment_source">>
) {
  initDb();
  const current = db.getFirstSync<ReminderRow>("SELECT * FROM payment_reminders WHERE id = ?", id);
  if (!current) return;
  const next = { ...current, ...patch };
  db.runSync(
    `UPDATE payment_reminders
     SET title = ?, amount_due = ?, due_date = ?, notes = ?, repeat_monthly = ?, is_paid = ?, paid_at = ?, payment_source = ?, updated_at = ?
     WHERE id = ?`,
    next.title,
    Math.max(0, next.amount_due),
    next.due_date,
    next.notes,
    next.repeat_monthly,
    next.is_paid,
    next.paid_at,
    next.payment_source,
    new Date().toISOString(),
    id
  );
}

export function deleteReminder(id: number) {
  initDb();
  db.runSync("DELETE FROM reminder_payment_history WHERE reminder_id = ?", id);
  db.runSync("DELETE FROM payment_reminders WHERE id = ?", id);
}

export function markReminderPaid(id: number, paymentSource: string) {
  initDb();
  const reminder = db.getFirstSync<ReminderRow>("SELECT * FROM payment_reminders WHERE id = ?", id);
  if (!reminder || reminder.is_paid === 1) return;
  const paidAt = new Date().toISOString();
  const source = paymentSource.trim() || "Manual";
  db.runSync(
    `UPDATE payment_reminders
     SET is_paid = 1, paid_at = ?, payment_source = ?, updated_at = ?
     WHERE id = ?`,
    paidAt,
    source,
    paidAt,
    id
  );
  db.runSync(
    `INSERT INTO reminder_payment_history (reminder_id, paid_at, amount, payment_source)
     VALUES (?, ?, ?, ?)`,
    id,
    paidAt,
    reminder.amount_due,
    source
  );
}

export function getReminderPaymentHistory() {
  initDb();
  return db.getAllSync<ReminderPaymentHistoryRow & { reminder_title: string }>(
    `SELECT h.*, r.title as reminder_title
     FROM reminder_payment_history h
     JOIN payment_reminders r ON r.id = h.reminder_id
     ORDER BY datetime(h.paid_at) DESC`
  );
}

